config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :payments, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @amount = 44.0
    @description = 'Um produto muito legal!!!!!!'
  end

  def create
    customer = Stripe::Customer.create({
      :email => params[:stripeEmail],
      :source => params[:stripeToken]
    })

    charge = Stripe::Charge.create({
      :customer => customer.id,
      :amount => params[:amount],
      :description => params[:description],
      :currency => 'brl'
    })
binding.break
    rescue Stripe::CardError => e
      redirect_to new_payment_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<p>
  <%= link_to 'pagamento', new_payment_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/new.html.erb
<%= form_with url: payments_path do |f| %>
  <label class="amount">
      <span>Preço: R$<%= @amount %></span>
  </label>

  <%= f.hidden_field :amount,      value: (@amount*100).to_i %>
  <%= f.hidden_field :description, value: @description %>

  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="<%= @description %>"
    data-amount="<%= @amount*100 %>"
    data-currency="brl"
    data-locale="pt-BR">
  </script>
<% end %>